
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/library'
    username: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
